#!/bin/bash

# Atualiza os repositórios e atualiza todos os pacotes
apt update -y && apt upgrade -y

# Desinstala a versão antiga do speedtest-cli
pip uninstall speedtest-cli -y
sudo apt-get remove speedtest-cli -y

# Instala o speedtest original
sudo apt-get install -y curl
curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
sudo apt-get install -y speedtest

# Executa o speedtest
sudo speedtest
